import Head from 'next/head';
import Image from 'next/image';
import Waitlist from './components/Waitlist';
import Tracks from './components/Tracks';
import Skills from './components/Skills';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Floxus Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Waitlist />
      <Tracks />
      <Skills />
    </div>
  );
}
